name: Deploy to Replit

on:
  push:
    branches:
      - main
      - release/staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc --noEmit

      - name: Run gallery validation tests
        run: node release-validation-test.js

      - name: Deploy to Replit
        run: echo "Deploy to Replit via their deployment system"