name: 🚀 Deploy Staging Branch to Vercel

on:
  push:
    branches:
      - release/staging

jobs:
  deploy:
    name: Deploy to Vercel (Staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Staging)
        run: npx vercel --token=${{ secrets.GH_PAT_KOLAKEVILLA }}
