name: Protect Feature Deletions
on: { pull_request: { branches: [ main, GuestyPro, fix/**, feat/** ] } }
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          dels=$(git diff --name-status "$base" "$head" | awk '$1=="D" && ($2 ~ /^app\/|^components\//){print $2}')
          if [ -n "$dels" ]; then
            echo "::error::Critical files deleted: $dels. Add label 'approved-removal' or include 'APPROVED-REMOVAL' in commit message."
            exit 1
          fi