name: Protect Lockfile / Dep Upgrades
on:
  pull_request:
    branches: [ main, GuestyPro, fix/**, feat/**, chore/** ]
jobs:
  lockfile-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Detect lockfile or package.json changes
        id: diff
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          git diff --name-only "$base" "$head" > changed.txt
          if grep -E '^(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|package\.json)$' changed.txt; then
            echo "depchange=1" >> $GITHUB_OUTPUT
          else
            echo "depchange=0" >> $GITHUB_OUTPUT
          fi
      - name: Require dep-upgrade-approved label
        if: steps.diff.outputs.depchange == '1'
        run: |
          label_ok=$(jq -r '.pull_request.labels[].name' <<< '${{ toJson(github.event) }}' | grep -i '^dep-upgrade-approved$' || true)
          if [ -z "$label_ok" ]; then
            echo "::error::Dependency changes detected. Add label 'dep-upgrade-approved' to proceed."
            exit 1
          fi