name: QA – GuestyPro Parity
on:
  pull_request:
    branches: [ main, GuestyPro, fix/**, feat/** ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: 'npm' }
      - run: npm ci || npm i
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Unit
        run: npx jest --coverage || npm run test:unit
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: E2E (local)
        run: |
          BASE_URL="http://127.0.0.1:3000" nohup npm run dev >/dev/null 2>&1 &
          npx wait-on http://127.0.0.1:3000
          npx playwright test
      - name: E2E (Vercel preview, if URL provided)
        if: ${{ github.event.pull_request.head.ref != '' && startsWith(github.event.pull_request.head.ref, '') }}
        env:
          BASE_URL: ${{ secrets.VERCEL_PREVIEW_URL }}
        run: |
          if [ -n "$BASE_URL" ]; then
            PW_NO_SERVER=1 npx playwright test
          else
            echo "No VERCEL_PREVIEW_URL secret set – skipping preview run."
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report